---
job:
  # We might not want to run the fidc configurator in all environments (for example Nightly) - setting to false will skip creating the fidc configurator in the cluster
  enabled: true
  environment:
    # Environment Settings for SAPIG & Cloud Platform
    # SAPIG
    # core: base sapig
    # ob: Open Banking specification of sapig
    sapigType: core
    # CDK value: (Cloud Developer's Kit) development identity platform
    # CDM value: CDM (Cloud Deployment Model) identity cloud platform
    # FIDC value: FIDC (Forgerock Identity Cloud) identity cloud platform
    frPlatformType: FIDC
    # RaiseForStatus will exit if go resty returns an error in STRICT mode,
    # be it client error, server error or other. Turning off (false)
    # STRICT mode will simply warn of client/server errors.
    strict: true
  image:
    # Repo And Tag are not provided here as the value for the repo will be unique for each user/customer as they will be building their own docker images and push to their own Container Registries 
    # The tag will use the .AppVersion as the default, meaning that customers who want to install V1 will get V1.0.0 of the software - you may supply a hard coded version if required  
    # The values for each of these should be supplied in the .Values folder of an individual deployment within the specification repository - See https://github.com/SecureApiGateway/SecureApiGateway/wiki/Deployment#repositories
    # repo:
    # tag:
    # We want to pull the image down each time we do a deployment, required if using 'latest' tag
    imagePullPolicy: Always
  # When to restart the pod
  restartPolicy: OnFailure