cron: "* * * * *"

# environment.type: It can be:
# CDK value: (Cloud Developer's Kit) development identity platform
# CDM value: CDM (Cloud Deployment Model) identity cloud platform
# FIDC value: FIDC (Forgerock Identity Cloud) identity cloud platform
environment:
  type: FIDC
  namespace: dev
  # the subdomain on which the platform will be available, e.g. iam.<subdomain>.forgerock.financial
  fr_platform:
    fqdn: iam.dev.forgerock.financial
  sbat: 
    domain: dev.forgerock.financial
  
  # RaiseForStatus will exit if go resty returns an error in STRICT mode,
  # be it client error, server error or other. Turning off (false)
  # STRICT mode will simply warn of client/server errors.
  strict: true
  cdmadminpassword: change

# The GCP project where the secret lives
projectId: sbat-dev
