apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: iam-init
spec:
  schedule: "{{ .Values.cron }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: iam-init
              image: eu.gcr.io/sbat-gcr-develop/securebanking/secureopenbanking-uk-fidc-initializer:latest
              imagePullPolicy: Always
              env:
                - name: ENVIRONMENT.STRICT
                  value: { { .Values.environment.strict | quote } }
                - name: HOSTS.IDENTITY_PLATFORM_FQDN
                  valueFrom:
                    configMapKeyRef:
                      name: platform-config
                      key: IDENTITY_PLATFORM_FQDN
                - name: HOSTS.RS_FQDN
                  valueFrom:
                    configMapKeyRef:
                      name: platform-config
                      key: RS_FQDN
                - name: HOSTS.RCS_UI_FQDN
                  valueFrom:
                    configMapKeyRef:
                      name: platform-config
                      key: RCS_UI_FQDN
                - name: HOSTS.IG_FQDN
                  valueFrom:
                    configMapKeyRef:
                      name: platform-config
                      key: IG_FQDN
                {{- if eq .Values.environment.type "FIDC" }}
                - name: USERS.CDM_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: initializer-secret
                      key: cdm-admin-password
                - name: USERS.CDM_ADMIN_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: initializer-secret
                      key: cdm-admin-user
                {{- else }}
                - name: USERS.CDM_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: am-env-secrets
                      key: AM_PASSWORDS_AMADMIN_CLEAR
                {{ end }}
              command: [ "/bin/sh", "-c" ]
              args:
                - |
                  echo "IDENTITY_PLATFORM_FQDN $HOSTS.IDENTITY_PLATFORM_FQDN"
                  until $(curl -X GET --output /dev/null --silent --head --fail -H "X-OpenIDM-Username: anonymous" \
                  -H "X-OpenIDM-Password: anonymous" -H "X-OpenIDM-NoSession: true" \
                  https://$HOSTS.IDENTITY_PLATFORM_FQDN/openidm/info/ping)
                  do
                  echo "IDM not ready"
                  sleep 10
                  done
                  ./setup
          restartPolicy: OnFailure
