name: merge

on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md

env:
  SERVICE_NAME: secureopenbanking-uk-iam-initializer
  GIT_SHA_SHORT: $(echo ${{ github.sha }} | cut -c1-7)

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout init config repo
        uses: actions/checkout@v3
        with:
          repository: SecureApiGateway/fr-platform-config
          path: config-repo
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          ref: master
      
      - name: Move config files
        run: |
          mkdir config
          mv config-repo/config/* config
          rm -rf config-repo

      - name: Run Tests
        run: |
          make test-ci

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCR_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

        # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker
      
      - name: docker build
        run: |
          make docker tag=${{ env.GIT_SHA_SHORT }}
          docker tag eu.gcr.io/${{ secrets.DEV_REPO }}/securebanking/${{ env.SERVICE_NAME }}:${{ env.GIT_SHA_SHORT }} eu.gcr.io/${{ secrets.DEV_REPO }}/securebanking/${{ env.SERVICE_NAME }}:latest
          docker push eu.gcr.io/${{ secrets.DEV_REPO }}/securebanking/${{ env.SERVICE_NAME }}:latest
