name: pr

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - README.md

env:
  SERVICE_NAME: securebanking-openbanking-uk-fidc-inilializer

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Tests
        run: |
          make test-ci
      
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_KEY }}
          export_default_credentials: true
        # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker

      - name: docker build
        run: |
          make docker
