name: pr

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - README.md

env:
  SERVICE_NAME: fidc-configurator
  PR_NUMBER: pr-${{ github.event.number }}

jobs:
  check:
    name: Check Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          make test-ci
  build:
    name: Build
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Auth to GCP  
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.DEV_GAR_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1

        # Configure docker to use the gcloud command-line tool as a credential helper
      - name: Auth Docker
        run: |
          gcloud auth configure-docker europe-west4-docker.pkg.dev

      - name: docker build
        run: |
          make docker tag=${{ env.PR_NUMBER }}

  test:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Create lowercase Github Username
        id: toLowerCase
        run: echo "GITHUB_USER=$(echo ${{github.actor}} | tr '[:upper:]' '[:lower:]')" >> ${GITHUB_ENV}

      - name: 'Deploy Service'
        uses: codefresh-io/codefresh-pipeline-runner@master
        if: github.actor != 'dependabot[bot]'
        with:
          args: '-v TAG=${{ env.PR_NUMBER }} -v ARGO_VALUES_PREFIX=fidcConfigurator -v SERVICE_NAME=fidc-configurator -v ENVIRONMENT=${{ env.GITHUB_USER }} -v BRANCH=${{ github.head_ref }}'
        env:
          PIPELINE_NAME: 'ForgeCloud/sbat-infra/service-build'
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          TRIGGER_NAME: github-actions-trigger-init
        id: run-pipeline