name: release

on:
  release:
    types: [ published ]

env:
  SERVICE_NAME: secureopenbanking-uk-fidc-initializer

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Tests
        run: |
          make test-ci

      - name: Auth to GCP  
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.DEV_GAR_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1

        # Configure docker to use the gcloud command-line tool as a credential helper
      - name: Auth Docker
        run: |
          gcloud auth configure-docker europe-west4-docker.pkg.dev
      
      - name: docker build
        run: |
          make docker release-repo=${{ vars.GAR_RELEASE_REPO }}
